name: Gem

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        with:
          supported-ruby-platforms: |
            exclude:
              - arm-linux
              - x86_64-linux-musl
              - x64-mingw-ucrt
              - x64-mingw32
          stable-ruby-versions: |
            exclude: [head]

  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
    - uses: actions/checkout@v4

    - name: Create registry dir
      run: |
        mkdir -p $HOME/.cargo/registry

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2'

    - uses: oxidize-rb/actions/cross-gem@v1
      id: cross-gem
      with:
        platform: ${{ matrix.platform }}
        ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}

    - name: Build and publish Gem
      env:
        GEM_HOST_API_KEY: ${{secrets.RUBYGEMS_TOKEN}}
      run: |
        gem push --KEY github --host https://rubygems.org ${{ steps.cross-gem.outputs.gem-path }}
