name: Gem

on:
  push:
    tags:
      - "v*"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-data:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.fetch.outputs.result }}
    steps:
      - uses: oxidize-rb/actions/fetch-ci-data@v1
        id: fetch
        with:
          supported-ruby-platforms: |
            exclude:
              - arm-linux
              - x86_64-linux-musl
              - x64-mingw-ucrt
              - x64-mingw32
          stable-ruby-versions: |
            exclude:
              - head

  cross-gem:
    name: Compile native gem for ${{ matrix.platform }}
    runs-on: ubuntu-latest
    needs: ci-data
    strategy:
      matrix:
        platform: ${{ fromJSON(needs.ci-data.outputs.result).supported-ruby-platforms }}
    steps:
    - uses: actions/checkout@v3
    - uses: oxidize-rb/actions/setup-ruby-and-rust@main
      with:
        ruby-version: "3.1"
        rustup-toolchain: "1.76.0"
        bundler-cache: true
        cargo-cache: true
    - uses: oxidize-rb/cross-gem-action@v1
      id: cross-gem
      with:
        platform: ${{ matrix.platform }}
        ruby-versions: ${{ join(fromJSON(needs.ci-data.outputs.result).stable-ruby-versions, ',') }}
        setup: bundle
    - uses: actions/upload-artifact@v2
      with:
        name: pgp-rb
        path: ${{ steps.cross-gem.outputs.gem-path }}
